-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\FrequencyGeneratorSystem.vhd
-- Created: 2016-09-07 21:17:00
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FrequencyGeneratorSystem
-- Source Path: mealy_moore/Meanly-Moore/moore_sf/FrequencyGeneratorSystem
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FrequencyGeneratorSystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        FreqIn                            :   IN    std_logic;
        FreqOut                           :   OUT   std_logic
        );
END FrequencyGeneratorSystem;


ARCHITECTURE rtl OF FrequencyGeneratorSystem IS

  -- Signals
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;

BEGIN
  -- <S13>/Delay
  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      Delay_out1 <= Logical_Operator_out1;
    END IF;
  END PROCESS Delay_process;


  -- <S13>/Logical Operator1
  Logical_Operator1_out1 <= FreqIn AND Delay_out1;

  -- <S13>/Logical Operator
  Logical_Operator_out1 <=  NOT Logical_Operator1_out1;

  FreqOut <= Logical_Operator_out1;

END rtl;

