-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\Function1.vhd
-- Created: 2016-09-07 21:12:22
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Function1
-- Source Path: mealy_moore/Meanly-Moore/Function1
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Function1 IS
  PORT( u                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END Function1;


ARCHITECTURE rtl OF Function1 IS

BEGIN
  --MATLAB Function 'Meanly-Moore/Function1': '<S3>:1'
  --'<S3>:1:4'
  y <= u;

END rtl;

