-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\Function_rsvd.vhd
-- Created: 2016-09-07 21:12:22
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Function_rsvd
-- Source Path: mealy_moore/Meanly-Moore/Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Function_rsvd IS
  PORT( u                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END Function_rsvd;


ARCHITECTURE rtl OF Function_rsvd IS

BEGIN
  --MATLAB Function 'Meanly-Moore/Function': '<S2>:1'
  --'<S2>:1:4'
  y <= u;

END rtl;

