-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\KingOfTHeHill.vhd
-- Created: 2016-09-07 21:17:00
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: KingOfTHeHill
-- Source Path: mealy_moore/Meanly-Moore/KingOfTHeHill
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY KingOfTHeHill IS
  PORT( u                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END KingOfTHeHill;


ARCHITECTURE rtl OF KingOfTHeHill IS

BEGIN
  --MATLAB Function 'Meanly-Moore/KingOfTHeHill': '<S4>:1'
  --'<S4>:1:4'
  y <= u;

END rtl;

