-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\MATLAB_Function.vhd
-- Created: 2016-09-07 21:10:33
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: mealy_moore/Meanly-Moore/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( u                                 :   IN    std_logic;
        y                                 :   OUT   std_logic
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

BEGIN
  --MATLAB Function 'Meanly-Moore/MATLAB Function': '<S2>:1'
  --'<S2>:1:4'
  y <= u;

END rtl;

