-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\Meanly_Moore.vhd
-- Created: 2016-09-07 20:29:42
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Meanly_Moore
-- Source Path: mealy_moore/Meanly-Moore
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Meanly_Moore IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        In1                               :   IN    std_logic;
        In2                               :   IN    std_logic;
        Out1                              :   OUT   std_logic;
        Out2                              :   OUT   std_logic;
        Out3                              :   OUT   std_logic;
        Out4                              :   OUT   std_logic
        );
END Meanly_Moore;


ARCHITECTURE rtl OF Meanly_Moore IS

  -- Component Declarations
  COMPONENT moore_sf
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          get_going                       :   IN    std_logic;
          ready                           :   OUT   std_logic;
          enable                          :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT mealy_sf
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          get_going                       :   IN    std_logic;
          ready                           :   OUT   std_logic;
          enable                          :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : moore_sf
    USE ENTITY work.moore_sf(rtl);

  FOR ALL : mealy_sf
    USE ENTITY work.mealy_sf(rtl);

  -- Signals
  SIGNAL ready                            : std_logic;
  SIGNAL counter_en                       : std_logic;
  SIGNAL ready_1                          : std_logic;
  SIGNAL counter_en_1                     : std_logic;

BEGIN
  u_moore_sf : moore_sf
    PORT MAP( clk => clk,
              reset => reset,
              get_going => In1,
              ready => ready,
              enable => counter_en
              );

  u_mealy_sf : mealy_sf
    PORT MAP( clk => clk,
              reset => reset,
              get_going => In2,
              ready => ready_1,
              enable => counter_en_1
              );

  Out1 <= ready;

  Out2 <= counter_en;

  Out3 <= ready_1;

  Out4 <= counter_en_1;

END rtl;

