vlib work
vcom  Meanly_Moore_pkg.vhd
vcom  Simple_Mealy_Chart.vhd
vcom  mealy_sf.vhd
vcom  FrequencyGeneratorSystem.vhd
vcom  Simple_Moore_Chart.vhd
vcom  moore_sf.vhd
vcom  FightToTheEnd.vhd
vcom  KingOfTHeHill.vhd
vcom  Meanly_Moore.vhd
