-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mealy_moore\Simple_Moore_Chart.vhd
-- Created: 2016-09-07 21:04:31
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Simple_Moore_Chart
-- Source Path: mealy_moore/Meanly-Moore/moore_sf/Simple_Moore_Chart
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Meanly_Moore_pkg.ALL;

ENTITY Simple_Moore_Chart IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        get_going                         :   IN    std_logic;
        count                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ready                             :   OUT   std_logic;
        count_en                          :   OUT   std_logic
        );
END Simple_Moore_Chart;


ARCHITECTURE rtl OF Simple_Moore_Chart IS

  -- Signals
  SIGNAL count_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL is_Simple_Moore_Chart            : T_state_type_is_Simple_Moore_Chart;  -- uint8

BEGIN
  count_unsigned <= unsigned(count);

  Simple_Moore_Chart_1_process : PROCESS (clk, reset)
    VARIABLE is_Simple_Moore_Chart_temp : T_state_type_is_Simple_Moore_Chart;
  BEGIN
    IF reset = '1' THEN
      --Entry: Meanly-Moore/moore_sf/Simple_Moore_Chart
      --Entry Internal: Meanly-Moore/moore_sf/Simple_Moore_Chart
      --Transition: '<S11>:12'
      is_Simple_Moore_Chart <= IN_IDLE;
    ELSIF clk'EVENT AND clk = '1' THEN
      is_Simple_Moore_Chart_temp := is_Simple_Moore_Chart;
      --Gateway: Meanly-Moore/moore_sf/Simple_Moore_Chart
      --During: Meanly-Moore/moore_sf/Simple_Moore_Chart
      CASE is_Simple_Moore_Chart IS
        WHEN IN_COUNTING =>
          --During 'COUNTING': '<S11>:7'
          IF count_unsigned = to_unsigned(16#19#, 8) THEN 
            --Transition: '<S11>:9'
            is_Simple_Moore_Chart_temp := IN_IDLE;
          END IF;
        WHEN OTHERS => 
          --During 'IDLE': '<S11>:5'
          IF get_going = '1' THEN 
            --Transition: '<S11>:8'
            is_Simple_Moore_Chart_temp := IN_COUNTING;
          END IF;
      END CASE;
      is_Simple_Moore_Chart <= is_Simple_Moore_Chart_temp;
    END IF;
  END PROCESS Simple_Moore_Chart_1_process;

  Simple_Moore_Chart_1_output : PROCESS (is_Simple_Moore_Chart)
    VARIABLE ready_temp : std_logic;
    VARIABLE count_en_temp : std_logic;
  BEGIN
    CASE is_Simple_Moore_Chart IS
      WHEN IN_COUNTING =>
        ready_temp := '0';
        count_en_temp := '1';
      WHEN OTHERS => 
        ready_temp := '1';
        count_en_temp := '0';
    END CASE;
    count_en <= count_en_temp;
    ready <= ready_temp;
  END PROCESS Simple_Moore_Chart_1_output;


END rtl;

