vlib work
vcom  LogicPRocessor_pkg.vhd
vcom  Simple_Mealy_Chart.vhd
vcom  mealy_sf.vhd
vcom  mealy_sf1.vhd
vcom  mealy_sf2.vhd
vcom  mealy_sf3.vhd
vcom  Simple_Moore_Chart.vhd
vcom  moore_sf.vhd
vcom  moore_sf1.vhd
vcom  moore_sf2.vhd
vcom  moore_sf3.vhd
vcom  LogicPRocessor.vhd
